In [1]:
import chess.pgn

In [2]:
pgn_file = open("../data/Theni21-white.pgn")

In [3]:
game = chess.pgn.read_game(pgn_file)

In [4]:
print(game)

[Event "Live Chess"]
[Site "Chess.com"]
[Date "2026.05.03"]
[Round "-"]
[White "Theni21"]
[Black "dontfalljamalCLONE"]
[Result "1/2-1/2"]
[CurrentPosition "5Q2/6pk/7p/p7/PpBP4/1P4P1/2pq3P/7K w - - 8 55"]
[Timezone "UTC"]
[ECO "D02"]
[ECOUrl "https://www.chess.com/openings/London-System-3...c5-4.e3-e6"]
[UTCDate "2026.05.03"]
[UTCTime "20:56:57"]
[WhiteElo "1440"]
[BlackElo "1459"]
[TimeControl "600"]
[Termination "Game drawn by repetition"]
[StartTime "20:56:57"]
[EndDate "2026.05.03"]
[EndTime "21:13:47"]
[Link "https://www.chess.com/game/live/168195289058"]

1. d4 d5 2. Nf3 Nf6 3. Bf4 e6 4. e3 c5 5. a3 c4 6. Nc3 Bd6 7. Bxd6 Qxd6 8. Be2 a6 9. Ne5 Nbd7 10. Nxd7 Bxd7 11. O-O b5 12. Bf3 O-O 13. b3 Rfe8 14. a4 b4 15. Na2 c3 16. Qd3 a5 17. Rfe1 Bc6 18. Re2 Bb7 19. Rae1 Ba6 20. Qd1 Bxe2 21. Qxe2 Qa6 22. Qd1 Qc6 23. Be2 Qd6 24. Bb5 Re7 25. Nc1 Ne8 26. Ne2 Nc7 27. Bd3 e5 28. Ng3 e4 29. Bf1 Ne8 30. Nf5 Qe6 31. Nxe7+ Qxe7 32. Qh5 Nf6 33. Qg5 h6 34. Qg3 Nh5 35. Qh3 Nf6 36. Bb5 Rb8 37. Qg3 Rb6 38

In [5]:
board = game.board()

In [6]:
for move in game.mainline_moves():
    print(board.fen())
    print("Move played:", move)
    print("---")
    board.push(move)

rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
Move played: d2d4
---
rnbqkbnr/pppppppp/8/8/3P4/8/PPP1PPPP/RNBQKBNR b KQkq - 0 1
Move played: d7d5
---
rnbqkbnr/ppp1pppp/8/3p4/3P4/8/PPP1PPPP/RNBQKBNR w KQkq - 0 2
Move played: g1f3
---
rnbqkbnr/ppp1pppp/8/3p4/3P4/5N2/PPP1PPPP/RNBQKB1R b KQkq - 1 2
Move played: g8f6
---
rnbqkb1r/ppp1pppp/5n2/3p4/3P4/5N2/PPP1PPPP/RNBQKB1R w KQkq - 2 3
Move played: c1f4
---
rnbqkb1r/ppp1pppp/5n2/3p4/3P1B2/5N2/PPP1PPPP/RN1QKB1R b KQkq - 3 3
Move played: e7e6
---
rnbqkb1r/ppp2ppp/4pn2/3p4/3P1B2/5N2/PPP1PPPP/RN1QKB1R w KQkq - 0 4
Move played: e2e3
---
rnbqkb1r/ppp2ppp/4pn2/3p4/3P1B2/4PN2/PPP2PPP/RN1QKB1R b KQkq - 0 4
Move played: c7c5
---
rnbqkb1r/pp3ppp/4pn2/2pp4/3P1B2/4PN2/PPP2PPP/RN1QKB1R w KQkq - 0 5
Move played: a2a3
---
rnbqkb1r/pp3ppp/4pn2/2pp4/3P1B2/P3PN2/1PP2PPP/RN1QKB1R b KQkq - 0 5
Move played: c5c4
---
rnbqkb1r/pp3ppp/4pn2/3p4/2pP1B2/P3PN2/1PP2PPP/RN1QKB1R w KQkq - 0 6
Move played: b1c3
---
rnbqkb1r/pp3ppp/4pn2/3p4/2pP1B2/P1N1PN2/1PP2PPP/R

In [7]:
import numpy as np
import chess

def fen_to_tensor(fen):
    board = chess.Board(fen)
    tensor = np.zeros((12, 8, 8), dtype=np.float32)
    
    piece_to_layer = {
        (chess.PAWN, chess.WHITE): 0,
        (chess.KNIGHT, chess.WHITE): 1,
        (chess.BISHOP, chess.WHITE): 2,
        (chess.ROOK, chess.WHITE): 3,
        (chess.QUEEN, chess.WHITE): 4,
        (chess.KING, chess.WHITE): 5,
        (chess.PAWN, chess.BLACK): 6,
        (chess.KNIGHT, chess.BLACK): 7,
        (chess.BISHOP, chess.BLACK): 8,
        (chess.ROOK, chess.BLACK): 9,
        (chess.QUEEN, chess.BLACK): 10,
        (chess.KING, chess.BLACK): 11,
    }
    
    for square in chess.SQUARES:
        piece = board.piece_at(square)
        if piece:
            layer = piece_to_layer[(piece.piece_type, piece.color)]
            row = square // 8
            col = square % 8
            tensor[layer][row][col] = 1.0
    
    return tensor


In [8]:
starting_fen = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"
tensor = fen_to_tensor(starting_fen)

print("Shape:", tensor.shape)
print("\nWhite pawns layer:")
print(tensor[0])


Shape: (12, 8, 8)

White pawns layer:
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
def move_to_index(move):
    return move.from_square * 64 + move.to_square

def index_to_move(index):
    from_square = index // 64
    to_square = index % 64
    return chess.Move(from_square, to_square)


In [10]:


# take the first move from our game earlier
board = game.board()
first_move = list(game.mainline_moves())[0]

print("Move:", first_move)
print("Index:", move_to_index(first_move))
print("Back to move:", index_to_move(move_to_index(first_move)))

Move: d2d4
Index: 731
Back to move: d2d4


In [11]:
def load_games(pgn_path, your_username):
    X = []
    y = []
    
    pgn_file = open(pgn_path)
    game_count = 0
    
    while True:
        game = chess.pgn.read_game(pgn_file)
        if game is None:
            break
        
        headers = game.headers
        white = headers["White"]
        black = headers["Black"]
        
        # figure out which color you played
        if white == your_username:
            your_color = chess.WHITE
        elif black == your_username:
            your_color = chess.BLACK
        else:
            continue
        
        board = game.board()
        for move in game.mainline_moves():
            # only learn from your moves, not opponent's
            if board.turn == your_color:
                X.append(fen_to_tensor(board.fen()))
                y.append(move_to_index(move))
            board.push(move)
        
        game_count += 1
        if game_count % 100 == 0:
            print(f"Processed {game_count} games...")
    
    print(f"Done. Total games: {game_count}")
    return np.array(X), np.array(y)


In [12]:
X, y = load_games("../data/Theni21-white.pgn", "Theni21")

Processed 100 games...
Processed 200 games...
Processed 300 games...
Processed 400 games...
Processed 500 games...
Processed 600 games...
Processed 700 games...
Processed 800 games...
Processed 900 games...
Processed 1000 games...
Processed 1100 games...
Processed 1200 games...
Processed 1300 games...
Done. Total games: 1328


In [13]:
print("X shape:", X.shape)
print("y shape:", y.shape)


X shape: (46511, 12, 8, 8)
y shape: (46511,)


In [14]:
X_black, y_black = load_games("../data/Theni21-black.pgn", "Theni21")

# combine both files
X = np.concatenate([X, X_black])
y = np.concatenate([y, y_black])

print("Combined X shape:", X.shape)
print("Combined y shape:", y.shape)


Processed 100 games...
Processed 200 games...
Processed 300 games...
Processed 400 games...
Processed 500 games...
Processed 600 games...
Processed 700 games...
Processed 800 games...
Processed 900 games...
Processed 1000 games...
Processed 1100 games...
Processed 1200 games...
Processed 1300 games...
Done. Total games: 1341
Combined X shape: (91720, 12, 8, 8)
Combined y shape: (91720,)


In [15]:
from sklearn.model_selection import train_test_split

# first split off 10% for test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# then split remaining 10% for validation
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.111, random_state=42)

print("Training:", X_train.shape)
print("Validation:", X_val.shape)
print("Test:", X_test.shape)


Training: (73385, 12, 8, 8)
Validation: (9163, 12, 8, 8)
Test: (9172, 12, 8, 8)


In [16]:
import torch
import torch.nn as nn

class ChessNet(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.conv_layers = nn.Sequential(
            nn.Conv2d(12, 64, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Conv2d(128, 256, kernel_size=3, padding=1),
            nn.ReLU(),
        )
        
        self.fc_layers = nn.Sequential(
            nn.Flatten(),
            nn.Linear(256 * 8 * 8, 1024),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(1024, 4096),
        )
    
    def forward(self, x):
        x = self.conv_layers(x)
        x = self.fc_layers(x)
        return x


In [17]:
import torch.optim as optim

# setup
model = ChessNet()
optimizer = optim.Adam(model.parameters(), lr=0.001)
loss_fn = nn.CrossEntropyLoss()

# convert data to pytorch tensors
X_train_t = torch.tensor(X_train)
y_train_t = torch.tensor(y_train, dtype=torch.long)
X_val_t = torch.tensor(X_val)
y_val_t = torch.tensor(y_val, dtype=torch.long)

print("Setup done")
print("Model parameters:", sum(p.numel() for p in model.parameters()))


Setup done
Model parameters: 21352640


In [18]:
from torch.utils.data import TensorDataset, DataLoader

# batch the data
train_dataset = TensorDataset(X_train_t, y_train_t)
val_dataset = TensorDataset(X_val_t, y_val_t)

train_loader = DataLoader(train_dataset, batch_size=256, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=256)

print("Batches in training:", len(train_loader))


Batches in training: 287


In [21]:
EPOCHS = 20

for epoch in range(EPOCHS):
    # --- training ---
    model.train()
    total_loss = 0
    correct = 0
    total = 0

    for X_batch, y_batch in train_loader:
        optimizer.zero_grad()
        predictions = model(X_batch)
        loss = loss_fn(predictions, y_batch)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        correct += (predictions.argmax(1) == y_batch).sum().item()
        total += y_batch.size(0)

    train_acc = correct / total
    avg_loss = total_loss / len(train_loader)

    # --- validation ---
    model.eval()
    val_correct = 0
    val_total = 0

    with torch.no_grad():
        for X_batch, y_batch in val_loader:
            predictions = model(X_batch)
            val_correct += (predictions.argmax(1) == y_batch).sum().item()
            val_total += y_batch.size(0)

    val_acc = val_correct / val_total
    print(f"Epoch {epoch+1}/{EPOCHS} | Loss: {avg_loss:.4f} | Train Acc: {train_acc:.3f} | Val Acc: {val_acc:.3f}")


Epoch 1/20 | Loss: 2.0484 | Train Acc: 0.474 | Val Acc: 0.201
Epoch 2/20 | Loss: 1.7958 | Train Acc: 0.523 | Val Acc: 0.204
Epoch 3/20 | Loss: 1.5641 | Train Acc: 0.575 | Val Acc: 0.204
Epoch 4/20 | Loss: 1.3838 | Train Acc: 0.615 | Val Acc: 0.206
Epoch 5/20 | Loss: 1.2269 | Train Acc: 0.652 | Val Acc: 0.199
Epoch 6/20 | Loss: 1.1045 | Train Acc: 0.681 | Val Acc: 0.207
Epoch 7/20 | Loss: 1.0117 | Train Acc: 0.704 | Val Acc: 0.206


KeyboardInterrupt: 

In [22]:
torch.save(model.state_dict(), "../src/model.pth")
print("Model saved")


Model saved


In [23]:
X_test_t = torch.tensor(X_test)
y_test_t = torch.tensor(y_test, dtype=torch.long)

test_dataset = TensorDataset(X_test_t, y_test_t)
test_loader = DataLoader(test_dataset, batch_size=256)

model.eval()
test_correct = 0
test_total = 0

with torch.no_grad():
    for X_batch, y_batch in test_loader:
        predictions = model(X_batch)
        test_correct += (predictions.argmax(1) == y_batch).sum().item()
        test_total += y_batch.size(0)

test_acc = test_correct / test_total
print(f"Test Accuracy: {test_acc:.3f}")


Test Accuracy: 0.212
